# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\chengley\ups-relationship\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 522)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(717, 522))
        MainWindow.setMaximumSize(QtCore.QSize(717, 522))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(5, 9, 701, 471))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 1, 2, 1, 2)
        self.labell = QtWidgets.QLabel(self.formLayoutWidget)
        self.labell.setObjectName("labell")
        self.gridLayout_2.addWidget(self.labell, 0, 4, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_2.addWidget(self.textBrowser_2, 3, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 5, 1, 1, 1)
        self.pushButtonv = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonv.setObjectName("pushButtonv")
        self.gridLayout_2.addWidget(self.pushButtonv, 5, 3, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 5, 2)
        self.pushButtonr = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonr.setObjectName("pushButtonr")
        self.gridLayout_2.addWidget(self.pushButtonr, 5, 5, 1, 1)
        self.pushButtonshow = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonshow.setObjectName("pushButtonshow")
        self.gridLayout_2.addWidget(self.pushButtonshow, 8, 5, 1, 1)
        self.labelt = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelt.setText("")
        self.labelt.setObjectName("labelt")
        self.gridLayout_2.addWidget(self.labelt, 2, 2, 1, 2)
        self.listView = QtWidgets.QListView(self.formLayoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 1, 4, 3, 2)
        self.pushButtons = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtons.setObjectName("pushButtons")
        self.gridLayout_2.addWidget(self.pushButtons, 5, 4, 1, 1)
        self.labeld = QtWidgets.QLabel(self.formLayoutWidget)
        self.labeld.setText("")
        self.labeld.setObjectName("labeld")
        self.gridLayout_2.addWidget(self.labeld, 8, 2, 1, 2)
        self.pushButtonl = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonl.setObjectName("pushButtonl")
        self.gridLayout_2.addWidget(self.pushButtonl, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "少年Pi,api,A_Pi,少年PI,API"))
        self.labell.setText(_translate("MainWindow", "视频列表"))
        self.label_4.setText(_translate("MainWindow", "拉取量"))
        self.label.setText(_translate("MainWindow", "输入"))
        self.pushButtonv.setText(_translate("MainWindow", "获取视频数据"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9.06294pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">说明：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.06294pt;\">输入tag列表</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.06294pt;\">example:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.06294pt; font-weight:600;\">少年Pi,api,A_Pi,少年PI,API</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.06294pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.06294pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.06294pt;\">点击视频列表切换tag</span></p></body></html>"))
        self.pushButtonr.setText(_translate("MainWindow", "读取json"))
        self.pushButtonshow.setText(_translate("MainWindow", "展示数据表"))
        self.pushButtons.setText(_translate("MainWindow", "保存json"))
        self.pushButtonl.setText(_translate("MainWindow", "拉取视频列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tag->"))
        self.label_2.setText(_translate("MainWindow", "施工中..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "bvid->"))
